print ("What is your name?")
name = input()
print ("What is your organization?")
org = input()
print ("What is your email?")
email = input()
print ("What is your badge tier?")
badge_tier = input()
print ("|----------------------|")
print ("| ATTENDEE : " + name.ljust(10) + "|")
print ("| ORG : " + org.ljust(15) + "|")
print ("| EMAIL : " + email.ljust(13) + "|")
print ("| BADGE TIER : " + badge_tier.ljust(8) + "|")