print ("Welcome to the ASCII")
print ("What is your name?")
name = input()
print ("What is your organization?")
org = input()
print ("What is your email?")
email = input()
print ("What is your badge tier?")
badge_tier = input()
print ("|----------------------------------|")
print ("| ATTENDEE : " + name.ljust(22) + "|")
print ("| ORG : " + org.ljust(27) + "|")
print ("| EMAIL : " + email.ljust(25) + "|")
print ("| BADGE TIER : " + badge_tier.ljust(20) + "|")
print ("|----------------------------------|")