print("=== APEX ENTERTAINMENT ORDER KIOSK ===")
name = input("Enter customer first name: ")
tickets = int(input("Enter number of tickets: "))
meal_passes = int(input("Enter number of meal passes: "))
print("-" * 30)
print("RECEIPT FOR: " + name)
print("Admission Total: " + str(tickets * 18))
print("Meals Total: " + str(meal_passes * 12))
print("Meals Total: " + str(tickets * 18 + meal_passes * 12))